[package]
name = "jgero-me-webpage"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
leptos = { version = "0.5.2", features = ["ssr"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
