steps:
# build the portfolio image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest', '-f', './container/prod.Dockerfile', '.']
  dir: 'portfolio'
  timeout: 120s
# push the portfolio image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest']
# deploy portfolio image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'portfolio-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
# build the space image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/space-page:latest', '-f', './container/prod.Dockerfile', '.']
  dir: 'space'
  timeout: 120s
# push the space image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/space-page:latest']
# deploy space image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'space-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/space-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
# build the main image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/main-page:latest', '-f', './container/prod.Dockerfile', '.']
  dir: 'main'
  timeout: 120s
# push the main image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/main-page:latest']
# deploy space image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'main-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/main-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/portfolio-page:latest'
- 'gcr.io/$PROJECT_ID/space-page:latest'
- 'gcr.io/$PROJECT_ID/main-page:latest'
