steps:
# build the portfolio image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-page:$COMMIT_SHA', '-f', './container/prod.Dockerfile', '.']
  dir: 'portfolio'
  timeout: 120s
# push the portfolio image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/portfolio-page:$COMMIT_SHA']
# deploy portfolio image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'portfolio-page'
  - '--image'
  - 'gcr.io/$PROJECT_ID/portfolio-page:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
timeout: 140s
images:
- 'gcr.io/$PROJECT_ID/portfolio-page:$COMMIT_SHA']
