# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.1.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-25T12:41:28Z"
  labels:
    app: my-webpage
  name: my-webpage
spec:
  containers:
  - args:
    - npm
    - run
    - dev
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NODE_VERSION
      value: 14.16.1
    - name: YARN_VERSION
      value: 1.22.5
    image: localhost/my-webpage/sapper:dev
    name: romanticbhabha
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: TCP
    - containerPort: 10000
      hostPort: 10000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /app/src
      name: home-jgero-repos-my-webpage-web-src-host
    - mountPath: /app/static
      name: home-jgero-repos-my-webpage-web-static-host
    - mountPath: /app/rollup.config.js
      name: home-jgero-repos-my-webpage-web-rollup.config.js-host
    workingDir: /app
  dnsConfig: {}
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/jgero/repos/my-webpage/web/src
      type: Directory
    name: home-jgero-repos-my-webpage-web-src-host
  - hostPath:
      path: /home/jgero/repos/my-webpage/web/static
      type: Directory
    name: home-jgero-repos-my-webpage-web-static-host
  - hostPath:
      path: /home/jgero/repos/my-webpage/web/rollup.config.js
      type: File
    name: home-jgero-repos-my-webpage-web-rollup.config.js-host
status: {}

