name: Publish Docker image
on:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push portfolio Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get meta for docker image
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghrc.io/jgero/my-webpage/portfolio
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} 
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./portfolio
          file: ./portfolio/container/prod.Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

